# Compose the postgresql database and the back-end only
services:
  db:
    image: postgres:16-alpine
    restart: always # Always restart if db crashes
    environment: # Env variables
      POSTGRES_DB: secondspark
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password

  # Python backend service
  backend:
    build: . #path to backend docker file and application
    container_name: "python_backend"
    ports:
      - "5000:5000"
    environment: # Env variables
      DB_HOST: db
      DB_NAME: secondspark
      DB_USER: default # username for db
      DB_PASSWORD: password # Password for db
      DB_PORT: 5432
      DB_SETUP_STAT: 0

    depends_on:
      - db
